import { defineConfig } from 'tsup';
import { writeFileSync, mkdirSync, chmodSync, existsSync,copyFileSync } from 'node:fs';
import { join } from 'node:path';

const NODE_BUILTIN_MODULE_REGEX = /^(assert|buffer|child_process|cluster|crypto|dgram|dns|domain|events|fs|http|https|net|os|path|punycode|querystring|readline|stream|string_decoder|timers|tls|tty|url|util|v8|vm|zlib)$/;

// plugin to add missing `node:` prefix - which is required for deno
function addNodeImportPrefix() {
  return {
    name: 'addNodeImportPrefix',
    setup(build) {
    
      build.onResolve({ filter: NODE_BUILTIN_MODULE_REGEX }, function(args){
        
        return {
        path: `node:${args.path}`,
        external: true
      }})
    },
  }
}


// Bin wrapper templates
const BIN_SCRIPTS = {
  overseer: `#!/bin/sh
# Auto-generated by tsup. Polyglot bootstrap: Bun → Deno → Node
# Resolves symlinks to find the real package location.

SCRIPT_PATH="$0"
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  case "$SCRIPT_PATH" in
    /*) ;;
    *) SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH" ;;
  esac
done
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
CLI="$SCRIPT_DIR/cli.js"

if command -v bun >/dev/null 2>&1; then
  exec bun "$CLI" "$@"
fi
if command -v deno >/dev/null 2>&1; then
  exec deno run -A --unstable-sloppy-imports --unstable-net "$CLI" "$@"
fi
if command -v node >/dev/null 2>&1; then
  exec node "$CLI" "$@"
fi

echo "Error: No supported runtime found (bun, deno, or node)" >&2
exit 1
`,
  'overseer-node': `#!/bin/sh
SCRIPT_PATH="$0"
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  case "$SCRIPT_PATH" in /*) ;; *) SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH" ;; esac
done
exec node "$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/cli.js" "$@"
`,
  'overseer-bun': `#!/bin/sh
SCRIPT_PATH="$0"
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  case "$SCRIPT_PATH" in /*) ;; *) SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH" ;; esac
done
exec bun "$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/cli.js" "$@"
`,
  'overseer-deno': `#!/bin/sh
SCRIPT_PATH="$0"
while [ -L "$SCRIPT_PATH" ]; do
  SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  SCRIPT_PATH="$(readlink "$SCRIPT_PATH")"
  case "$SCRIPT_PATH" in /*) ;; *) SCRIPT_PATH="$SCRIPT_DIR/$SCRIPT_PATH" ;; esac
done
exec deno run -A --unstable-sloppy-imports --unstable-net "$(cd "$(dirname "$SCRIPT_PATH")" && pwd)/cli.js" "$@"
`,
};

// ESM __dirname shim — lets cli.js resolve files relative to itself
// even when invoked via symlink from a different directory.
const ESM_DIRNAME_SHIM = `import { fileURLToPath as __fileURLToPath } from 'node:url';
import { dirname as __dirnameFn } from 'node:path';
const __filename = __fileURLToPath(import.meta.url);
const __dirname = __dirnameFn(__filename);
`;

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    cli: 'src/cli.ts',
  },
  format: ['esm'],
  shims:true,
  dts:false,
  esbuildPlugins: [addNodeImportPrefix()],
  esbuildOptions(options, context) {
    options.platform = "neutral"
  },
  clean: true, 
  splitting: false,
  sourcemap: true,
  target: 'es2022',
  outDir: 'dist',
  platform:"neutral",
  // Bundle everything except the runtimes and peer deps
  external: [
    'cac',
    '@rabbx/config',
    '@rabbx/watcher',
    '@rabbx/ms',
    '@rabbx/colors',"node:*"
  ],
  
  // Inject __dirname shim only into cli.js (index.ts doesn't need it)
  banner(ctx) {
    if (ctx.format === 'esm' && ctx.name === 'cli') {
      return { js: ESM_DIRNAME_SHIM };
    }
    return {};
  },
  
  // Generate bin scripts after build
  async onSuccess() {
    const binDir = join(process.cwd(), 'dist', 'bin');
    
    if (!existsSync(binDir)) {
      mkdirSync(binDir, { recursive: true });
    }
    
    for (const [name, content] of Object.entries(BIN_SCRIPTS)) {
      const binPath = join(binDir, name);
      writeFileSync(binPath, content, { mode: 0o755 });
      chmodSync(binPath, 0o755);
    }
    try {
  copyFileSync('./dist/cli.js', './dist/bin/cli.js');
  console.log('File copied successfully!');
} catch (error) {
  console.error('Error copying file:', error);
}
    console.log('[tsup] Generated bin scripts in dist/bin/');
  },
});